### ISSUE TITLE
[Client] UI 화면 종료 처리

### ISSUE THREAD

**Issue by happineer** [happineer/SWArchitect2021#33]
* 테스트 환경: Client 프로그램을 수행하고 있는 상태

* 이슈: "X" 버튼을 눌러서, Client 종료했는데, 이클립스 로그를 보면 프로그램이 계속 돌고 있음.

**Comment by idoun** [comment]
수정 커밋 올렸습니다.

**Comment by happineer** [comment]
어? 어떻게 보셨지...ㅋㅋ
